/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ToolUI;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author kamin
 */
public class ThermoRelabelFrame extends javax.swing.JFrame {

    private ArrayList<ThermoSample> database;
    public JLabel titleLabel;
    public FocusTextField titleField;
    public FocusTextField[] entries;
    public JLabel[] samples;
    public int numSamples;
    public boolean entriesRead; //Variable that checks when user has approved input
    /**
     * Creates new form ThermoRelabelFrame
     */
    public ThermoRelabelFrame(ArrayList<ThermoSample> allData) {
        initComponents();
        entriesRead = false;
        database = allData;
        numSamples = allData.size();
        
        titleField = new FocusTextField();
        entries = new FocusTextField[numSamples];
        
        titleLabel = new JLabel("Title");
        samples = new JLabel[numSamples];
        
        for (int i = 0; i < numSamples; i++){
            samples[i] = new JLabel(allData.get(i).getLabel());
            entries[i] = new FocusTextField();
        }
        
        GroupLayout layout = new GroupLayout(reLabelPanel);
        reLabelPanel.setLayout(layout);
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);
        GroupLayout.SequentialGroup horizontalGroups = layout.createSequentialGroup();
        GroupLayout.SequentialGroup verticalGroups = layout.createSequentialGroup();
        
        GroupLayout.ParallelGroup allLabels = layout.createParallelGroup(GroupLayout.Alignment.LEADING);
        GroupLayout.ParallelGroup allFields = layout.createParallelGroup(GroupLayout.Alignment.LEADING);
        allLabels.addComponent(titleLabel);
        allFields.addComponent(titleField);
        verticalGroups.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(titleLabel).addComponent(titleField));
        
        
        for (int i = 0; i < numSamples; i++) {
            GroupLayout.ParallelGroup thisRow = layout.createParallelGroup(GroupLayout.Alignment.BASELINE);
            thisRow.addComponent(samples[i]).addComponent(entries[i]);
            verticalGroups.addGroup(thisRow);
            
            allLabels.addComponent(samples[i]);
            allFields.addComponent(entries[i]);
        }
        
        horizontalGroups.addGroup(allLabels).addGroup(allFields);
        layout.setHorizontalGroup(horizontalGroups);
        layout.setVerticalGroup(verticalGroups);
        
        this.pack();
        this.setVisible(true);
        
    }
    
    public ArrayList<ThermoSample> waitForInput(){
        return database;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        reLabelScroller = new javax.swing.JScrollPane();
        reLabelPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("APPLY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reLabelPanelLayout = new javax.swing.GroupLayout(reLabelPanel);
        reLabelPanel.setLayout(reLabelPanelLayout);
        reLabelPanelLayout.setHorizontalGroup(
            reLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );
        reLabelPanelLayout.setVerticalGroup(
            reLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        reLabelScroller.setViewportView(reLabelPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reLabelScroller)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reLabelScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        readFields();        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //Method to scan through all text fields and read user input, storing by replacing the name in the database
    public void readFields(){
        for (int i = 0; i < numSamples; i++){
            String entry = entries[i].getText();
            database.get(i).label(entry);
        }
        entriesRead = true;
    }
    
    static class FocusTextField extends JTextField {
    {
        addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                FocusTextField.this.select(0, getText().length());
            }

            @Override
            public void focusLost(FocusEvent e) {
                FocusTextField.this.select(0, 0);
            }
        });
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel reLabelPanel;
    private javax.swing.JScrollPane reLabelScroller;
    // End of variables declaration//GEN-END:variables
}
