/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ToolUI;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import javax.swing.*;
/**
 *
 * @author kamin
 */
public class ThermoAnalysis extends javax.swing.JFrame {
    private File chosenFolder;
    public Font official_font = null;
    /**
     * Creates new form ThermoAnalysis
     */
    public ThermoAnalysis(Font officialFont) {
        initComponents();
        official_font = officialFont;
        DiAssessDataAnalysisToolUI.applyFont(this, official_font);
        
    }

    
    public void setFileChooserFont(Component[] comp)
    {
        for(int x = 0; x < comp.length; x++)
        {
        if(comp[x] instanceof Container) setFileChooserFont(((Container)comp[x]).getComponents());
            try
            {
                comp[x].setFont(official_font);
            }
            catch(Exception e)
            {
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fileSelector = new javax.swing.JButton();
        fileNameField = new javax.swing.JTextField();
        fileLoader = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thermocycler Data Analysis Tool");

        fileSelector.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        fileSelector.setText("Select a folder...");
        fileSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSelectorActionPerformed(evt);
            }
        });

        fileNameField.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        fileNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameFieldActionPerformed(evt);
            }
        });

        fileLoader.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        fileLoader.setText("Load");
        fileLoader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileLoaderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1404, Short.MAX_VALUE)
                    .addComponent(fileLoader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fileSelector, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                        .addGap(84, 84, 84)
                        .addComponent(fileNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fileNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(fileSelector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addComponent(fileLoader, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSelectorActionPerformed
            JFileChooser chooser = new JFileChooser();
            setFileChooserFont(chooser.getComponents());
           
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            
            int returnVal = chooser.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION){
                chosenFolder = chooser.getSelectedFile();
                fileNameField.setText(chosenFolder.getAbsolutePath());
            }
    }//GEN-LAST:event_fileSelectorActionPerformed

    private void fileNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameFieldActionPerformed

    private void fileLoaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileLoaderActionPerformed
        // TODO add your handling code here:
        if (chosenFolder == null){
            JOptionPane.showMessageDialog(this,"Please select a folder to load");
        } else {
            ThermoLoadingFrame loadData = new ThermoLoadingFrame(chosenFolder,official_font);
            loadData.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            loadData.setVisible(true);
        }
        
    }//GEN-LAST:event_fileLoaderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fileLoader;
    private javax.swing.JTextField fileNameField;
    private javax.swing.JButton fileSelector;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
