/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ToolUI;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.image.BufferedImage;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author kamin
 */
public class TubeLabeler extends javax.swing.JFrame {

    JLabel[] allCroppedImages;
    FocusTextField[] textArray;
    /**
     * Creates new form TubeLabeler
     */
    public TubeLabeler() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void showData(int[] tubeLocationsX, int tubeLocationY, BufferedImage image){
         int yRange = 70;
               
                int numTubes = tubeLocationsX.length;
                GroupLayout myLayout = new GroupLayout(tubePanel);
                tubePanel.setLayout(myLayout);
                
                myLayout.setAutoCreateGaps(true);
                myLayout.setAutoCreateContainerGaps(true);
                
                
              
                textArray = new FocusTextField[numTubes];
                allCroppedImages = new JLabel[numTubes];
                
                GroupLayout.SequentialGroup horGroup = myLayout.createSequentialGroup();
                GroupLayout.ParallelGroup pictureGroup = myLayout.createParallelGroup();
                GroupLayout.ParallelGroup textGroup = myLayout.createParallelGroup();
                
                for (int x = 0; x < tubeLocationsX.length; x++){
                    int xcor = tubeLocationsX[x]-77;
                    BufferedImage crop = image.getSubimage(xcor-60,tubeLocationY-4*yRange,120,yRange*5);
                    textArray[x] = new FocusTextField();

                    if(x != 0){
                        textArray[x].setText("Same as tube to the left");
                    } else {
                        textArray[x].setText("Enter a label for this tube");
                    }
                    allCroppedImages[x] = new JLabel(new ImageIcon(crop));
                    horGroup.addGroup(myLayout.createParallelGroup()
                            .addComponent(allCroppedImages[x])
                            .addComponent(textArray[x]));
                    
                    pictureGroup.addComponent(allCroppedImages[x]);
                    textGroup.addComponent(textArray[x]);
                }
                
                myLayout.setHorizontalGroup(horGroup);
                myLayout.setVerticalGroup(myLayout.createSequentialGroup()
                        .addGroup(pictureGroup)
                        .addGroup(textGroup));
                
                
                this.pack();
                this.setVisible(true);
                
    }
    
    public JTextField[] getLabels(){
        return textArray;
    }
    
    public JButton getButton(){
        return jButton1;
    }
    
     static class FocusTextField extends JTextField {
    {
        addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent e) {
                FocusTextField.this.select(0, getText().length());
            }

            @Override
            public void focusLost(FocusEvent e) {
                FocusTextField.this.select(0, 0);
            }
        });
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tubePanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout tubePanelLayout = new javax.swing.GroupLayout(tubePanel);
        tubePanel.setLayout(tubePanelLayout);
        tubePanelLayout.setHorizontalGroup(
            tubePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tubePanelLayout.setVerticalGroup(
            tubePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        jButton1.setText("Save this rack's data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tubePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tubePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TubeLabeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TubeLabeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TubeLabeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TubeLabeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TubeLabeler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel tubePanel;
    // End of variables declaration//GEN-END:variables
}
